author = bgstack15
depends = mcl_localplayer
description = Enables mcl_localplayer interactions with hot air balloons
license = LGPL-2.1-only
min_minetest_version = 5.11
name = csm_hot_air_balloons
optional_depends =
supported_games = mineclonia
title = Hot Air Balloons CSM for mcl_localplayer
